language: python
sudo: false
dist: xenial

cache:
  pip: true
  directories:
    - $HOME/buildout-cache
    - $HOME/.buildout

before_install:
    - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
    - mkdir -p $HOME/.buildout
    - echo "[buildout]" > $HOME/.buildout/default.cfg
    - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
    - echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
    - echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis CI"

#matrix:
#    include:
#        - python: "2.7"
#          env: TOXENV=lint-py27,docs
#        - python: "3.7"
#          env: TOXENV=lint-py37,docs
#        - python: "2.7"
#          env: TOXENV=py27-packagetests
#        - python: "2.7"
#          env: TOXENV=py37-packagetests
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_content_type
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_behavior
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_portlet
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_theme_barceloneta
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_theme
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_view
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_viewlet
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-addon_vocabulary
#        - python: "2.7"
#          env: TOXENV=py27-skeletontests-template-theme_package

install:
    - travis_retry pip install -U tox tox-travis coveralls coverage

before_script:
  - 'export DISPLAY=:99.0'
  - export VERBOSE=true
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

script:
    - PYTEST_ADDOPTS="-s -vv" tox

after_success:
  - coverage combine
  - coveralls

# after_script:

notifications:
  email:
    recipients:
      - travis-reports@plone.com
      - {author}
    on_success: change
    on_failure: change
